### ISSUE TITLE
No selected item causes an infinite progress bar after download.

### ISSUE THREAD

**Issue by BUZZARDGTA** [Grub4K/kamyroll-gui#2]
"Download Subtitles" and "Download All" with no URLs to download will result in an infinite progress bar loading.

I suggest adding a message box error instead.

![Kamyroll_2022-02-03_00-54](https://user-images.githubusercontent.com/62464560/152257477-51f7b582-7a43-46f9-b300-fd6221a170bc.png)

**Comment by Grub4K** [comment]
This is fixed by 893a55d1b3d562b072d81755b13e0c026ac38a0f already
